---
matrix:
  include:
    - name: Markdown Linting
      stage: lint
      language: ruby
      rvm:
        - "2.7"
      install:
        - gem install mdl
        - echo -e "all\nrule 'MD013', :line_length => 120" > custom_rules.rb
      script:
        - mdl . --style custom_rules.rb

    - name: Python Linting
      stage: lint
      language: python
      python:
        - "3.8"
      install:
        - pip install flake8
      script:
        - flake8 . --max-line-length=120

    - name: Latex Linting
      stage: lint
      install:
        - sudo apt-get install texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended
        - sudo apt-get install chktex
      script:
        - chktex -W  # Print version information.
        # We ignore 4 warnings described below:
        # Warning 3:  You should enclose the previous parenthesis with ‘{}’.
        #             Reason: https://tex.stackexchange.com/questions/529937/why-should-i-enclose-the-previous-parenthesis-with
        # Warning 6:  No italic correction (‘\/’) found.
        #             Reason: https://tex.stackexchange.com/questions/469942/chktex-complains-about-no-italic-correction-found-how-to-fix-this
        # Warning 8:  Wrong length of dash may have been used
        #             Reason: https://tex.stackexchange.com/questions/350485/how-to-ignore-wrong-length-of-dash-may-have-been-used-inside-cite-and-newci/418010
        #             TODO: Appending `% chktex 8` to the end of the offending line will ifgnore this check
        #             TODO: Changing image names to use underscores instead of hyphens will fix the issue
        # Warning 24: Delete this space to maintain correct pagereferences
        #             Reason: https://tex.stackexchange.com/questions/264109/when-is-leading-opening-whitespace-of-a-line-in-a-tex-file-important
        #             It's being overly cautious about the tab/spaces before a \label instace. But this
        #               shouldn't impact spacing, so we ignore them for now.
        - chktex -q -n 3 -n 6 -n 8 -n 24 */*.tex chapters.*.tex 2>/dev/null | tee lint.out
        # If lint output is non-empty report an error.
        - test ! -s lint.out

notifications:
  email: false
