---
matrix:
  include:
    - name: Markdown Linting
      stage: lint
      language: ruby
      rvm:
        - "2.7"
      install:
        - gem install mdl
        - echo -e "all\nrule 'MD013', :line_length => 120" > custom_rules.rb
      script:
        - mdl . --style custom_rules.rb

    - name: Python Linting
      stage: lint
      language: python
      python:
        - "3.8"
      install:
        - pip install flake8
      script:
        - flake8 . --max-line-length=120

notifications:
  email: false
