# shellcheck shell=bash
# Shared list of math assignment and presentation topics.
# shellcheck disable=SC2034  # Referenced by scripts that source this file.
topics=(
"Assignment 2 on Free Groups"
"Extending Conditional Recurrences over Finite Fields"
"Groups Generated by Reflections"
"Interpreting Meta-Fibonacci Recursions using Sum Trees"
"Proof on the Uniqueness of the Sicherman Dice"
"Solving Linear Relations using Linear Algebra"
"Theorems for 2nd Half of Graph Theory Course"
"Two Proofs of Cayley's Formula for the Number of Trees"
)
