#!/usr/bin/env bash
set -e

source_paths=(
"Assignment 2 on Free Groups/paper.pdf"
"Extending Conditional Recurrences over Finite Fields/paper.pdf"
"Groups Generated by Reflections/paper.pdf"
"Proof on the Uniqueness of the Sicherman Dice/paper.pdf"
"Solving Linear Relations using Linear Algebra/paper.pdf"
"Theorems for 2nd Half of Graph Theory Course/paper.pdf"
"Two Proofs of Cayley's Formula for the Number of Trees/presentation.pdf"
)

push_to_gdrive() {
  source_path="$1"
  destination_path="$(echo "${source_path}" | tr '/' ' ' | tr -d "'" | sed 's/paper.pdf/Paper.pdf/' | sed 's/presentation.pdf/Presentation.pdf/')"

  echo "Checking if the file ${destination_path} exists in Google Drive..."
  check=$(gdrive files list --query "name = '${destination_path}'" --skip-header | wc -l)
  echo "Found ${check} instance(s) of the file named ${destination_path}."

  if [ "${check}" -gt 1 ]; then
    echo "Too many instances. Exiting early..."
  fi

  source_dir="$(dirname "${source_path}")"
  source_path_to_upload="${source_dir}/${destination_path}"
  cp "${source_path}" "${source_path_to_upload}"

  if [ "${check}" -eq 1 ]; then
    echo -n "It exists. Attempting to fetch the file ID... "
    samefileID=$(gdrive files list --query "name = '${destination_path}'" --skip-header | sed 's/|/ /' | awk '{print $1}' | head -n 1)
    echo "Fetched the file ID. It's ${samefileID}."
    gdrive files update "${samefileID}" "${source_path_to_upload}"
  else
    echo "It doesn't exist. We'll upload the file."
    gdrive files upload "${source_path_to_upload}"
  fi

  rm -f "${source_path_to_upload}"
  echo "Done uploading."
  echo
}

for source_path in "${source_paths[@]}"; do
  push_to_gdrive "${source_path}"
done
