#!/usr/bin/env bash

topics=(
"Assignment 2 on Free Groups"
"Extending Conditional Recurrences over Finite Fields"
"Groups Generated by Reflections Paper"
"Proof on the Uniqueness of the Sicherman Dice"
"Solving Linear Relations using Linear Algebra"
"Theorems for 2nd Half of Graph Theory Course"
"Two Proofs of Cayley's Formula for the Number of Trees"
)

run_pdflatex() {
    local tex_directory=$1
    local tex_file=$2
    local tex_path="${tex_directory}/${tex_file}"
    echo "Building ${tex_path}..."
    cd "${tex_directory}" || exit
    if pdflatex -halt-on-error "${tex_file}"; then
        echo -e "$(tput setaf 2)Compiling ${tex_path} was successful!$(tput sgr0)"
    else
        echo -e "$(tput setaf 1)There was an error compiling ${tex_path}.$(tput sgr0)"
    fi
    echo
    cd ..
}

# Print all items in the array, just to demonstrate
for topic in "${topics[@]}"; do
    if [ -f "${topic}/paper.tex" ]; then
        run_pdflatex "${topic}" "paper.tex"
    elif [ -f "${topic}/presentation.tex" ]; then
        run_pdflatex "${topic}" "presentation.tex"
    else
        echo "Couldn't find ${topic}/paper.tex nor ${topic}/presentation.tex. Exiting..."
        exit 1
    fi
done
